### ISSUE TITLE
用termux安装appium-python-client各种报错

### ISSUE THREAD

**Issue by drakcraft** [JTiger0431/DingdongHelper#1]
请问你是装这个库的 谢谢

**Comment by JTiger0431** [comment]
请参考这里 https://github.com/appium/python-client 谢谢

**Comment by drakcraft** [comment]
非常感谢
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps) 请问这里是保持不变吗
我在adb connect状态电脑运行出现如下报错 

Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "D:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Python\Python37\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "D:\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "D:\Python\Python37\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\Python\Python37\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001BA24967160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/WorstRivenSH/Desktop/main1.py", line 201, in <module>
    job()
  File "C:/Users/WorstRivenSH/Desktop/main1.py", line 187, in job
    driver = init()
  File "C:/Users/WorstRivenSH/Desktop/main1.py", line 41, in init
    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
  File "D:\Python\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 275, in __init__
    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Python\Python37\lib\site-packages\appium\webdriver\webdriver.py", line 369, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 423, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 333, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 355, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "D:\Python\Python37\lib\site-packages\urllib3\request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "D:\Python\Python37\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\Python\Python37\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 826, in urlopen
    **response_kw
  File "D:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 826, in urlopen
    **response_kw
  File "D:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 826, in urlopen
    **response_kw
  File "D:\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BA24967160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

Process finished with exit code 1

**Comment by JTiger0431** [comment]
需要先运行 appium，4723 是 appium 的默认端口，所以这里无需改动

**Comment by drakcraft** [comment]
卧槽 我跑起来了 非常感谢
